name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy to GitHub Pages
    uses: JamesIves/github-pages-deploy-action@v4.4.0

      env:
        ACCESS_TOKEN: ${{ secrets.SECRET }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
