name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'double'
          ssh-key: ${{ secrets.Secret }}
      - run: |
          git add .
          git commit -m "generated"
          git push

